# Site settings
title: Avi Fox-Rosen
email: frosenox@gmail.com
description: "Web developer, musician, recording fanatic, baker."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
